### ISSUE TITLE
add monoDX to wine-staging

### ISSUE THREAD

**Issue by Eignar17** [alesliehughes/monoDX#1]
@alesliehughes add monoDX in to wine-staging could improve this implementation and be included in future wine sales

**Comment by alesliehughes** [comment]
Nice idea.  A thought I've had for a while, is to create an installer, like wine-mono, to make it easy for users to install.  
Maybe once an installer is crated, it could be possible.

**Comment by Eignar17** [comment]
yes and add install to wine-staging and test or view your monoDX for wine
